import Head from 'next/head';
import Header from '../components/Header';
import Navigatie from '../components/Nav';
import Rezultate from '../components/Results';
import GenuriFilmRequests from '../utils/requests';

export default function Home({ results: datePrimite }) {
  return (
    <div>
      <Head>
        <title>Aplicatie Filme - PLF</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      {/* Header */}
      <Header></Header>

      {/* Nav */}
      <Navigatie />

      {/* Results */}
      <Rezultate results={datePrimite} />
    </div>
  );
}

export async function getServerSideProps(continutJSON) {
  const genulFilmului = continutJSON.query.genre;

  const request = await fetch(
    `https://api.themoviedb.org/3${GenuriFilmRequests[genulFilmului]?.url || GenuriFilmRequests.fetchTrending.url}`
  ).then((res) => res.json());

  return {
    props: {
      results: request.results,
    },
  };
}
